apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-gateway-secret
  namespace: ai-gateway
spec:
  template:
    type: Opaque
  encryptedData:
    # replace with sealed secret values
    rabbitmq_url: AgB2...
    database_url: AgC3...
    jwt_secret: AgD4...
